# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RackScout' do

pod 'Firebase', '>= 2.3.2'
pod 'GeoFire', '>= 1.1'
pod 'GoogleMaps'
pod 'SMCalloutView'

end

target 'RackScoutTests' do

end

target 'RackScoutUITests' do

end

