# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RackScout' do

pod 'Firebase', '>= 2.3.2'
pod 'GeoFire', '>= 1.1'
pod 'GoogleMaps'
pod 'SMCalloutView'
pod 'JVFloatLabeledTextField'

end

target 'RackScoutTests' do

end

target 'RackScoutUITests' do

end

# post_install do | installer |
#    require 'fileutils'
#    FileUtils.cp_r('Pods/Target Support Files/Pods-RackScout/Pods-RackScout-Acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
# end
