# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'RackScout' do
pod 'Firebase', '>= 2.5.0'
end

target 'RackScoutTests' do
pod 'Firebase', '>= 2.5.0'
end

target 'RackScoutUITests' do
pod 'Firebase', '>= 2.5.0'
end

